version: "3"
services:
  app1:
    container_name: rss_gpt
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes: 
      - rss_gpt_logs:/app/logs
      - rss_gpt_db:/app  # This will store the database file

volumes:
  rss_gpt_logs:
  rss_gpt_db: