name: Flowersale_Bot_Parser

on:
  schedule:
    # Запуск каждые 4 часа
    - cron: '0 */4 * * *'
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Копируем файлы репозитория
        uses: actions/checkout@v3

      - name: Настраиваем Питон
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Устанавливаем библиотеки и браузер
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright
          # Устанавливаем сам браузер и зависимости для него
          playwright install chromium
          playwright install-deps

      - name: Запускаем бота
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          FLORI_COOKIES: ${{ secrets.FLORI_COOKIES }}
        run: python main.py
